msgbox"code by Nguyen Huy Hieu. tan huong di bro!"
msgbox"nay cu tan vao nhung em dem toi nay"
msgbox"cu tan trong man dem nay dam say"
msgbox"cu chon vui lang lo vao sang mai"
msgbox"chut yen binh chac dau can dung sai <3"
msgbox"Da chuchu"
msgbox"Da chuchu"
msgbox"Da chuchu"
msgbox"Da chuchu"
